service: som-qualtrics-survey-responses
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  memorySize: 256

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-east-2:916664006075:secret:eln-new-user-S3-dHxqkl"

    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : eln-new-user
            - "/*"
  environment:
    BUCKET: ${self:custom.outputBucket}
    QUALTRICS_API_TOKEN: ${self:custom.qualtricsApiToken.SOM_QUALTRICS_API_TOKEN}
    QUALTRICS_DATA_CENTER: "iad1"

custom:
  outputBucket: 'eln-new-user-${opt:stage, self:provider.stage}'
  qualtricsApiToken: ${ssm:/aws/reference/secretsmanager/eln-new-user-qualtrics-token~true}

functions:
  storeSurveys:
    timeout: 30
    handler: handler.storeSurveys
    events:
      - schedule: rate(15 minutes)
    environment:
      SURVEY_IDS: > 
        SV_3CNZ4441ph7WB8N

# you can add CloudFormation resource templates here
resources:
 Resources:
   SOMQualtricsSurveyResponseBucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:custom.outputBucket}
       PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
       BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
